rabbitmq:
  server: broker.sparkworks.net
  port: 5672
  username: CNIT
  password: c9ce97aa-3b71-446e-b3f4-f7130dfddb32
  queue:
    send: ${rabbitmq.username}-send
    receive: ${rabbitmq.username}-receive

netsens:
  url: http://live.netsens.it/export/xml_export_2A.php
  username: cnit
  password: cnit_pwd
  station: 723
  meter: last_reading
  baseURI: gaia-prato/gw1

meters:
  - QG/Lighting
  - Geom/GF/
  - Geom/1F
  - Geom/GF/Labs/MP
  - Geom/GF/Labs/Lighting
  - Geom/1F/Rooms/Lighting